config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      jsonapi_resources :balances, only: [:create, :destroy, :update]
      jsonapi_resources :financial_accounts, only: [:show]
      resource :sessions, only: [:create, :destroy]
    end
  end

  resources :households, only: :update
  resources :user_settings, only: [:update]
  resources :settings, only: [:index]
  resources :income_sources, only: [:create, :edit, :destroy, :index, :update, :new]
  resources :goals, only: [:index, :update]

  resources :assets, only: :show
  resources :liabilities, only: :show
  resources :financial_accounts do
    resources :balances, only: [:create, :destroy, :edit, :index, :show, :update]
    resources :financial_account_users, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :user_invites, only: [:create, :destroy] do
    member do
      put :resend
    end
  end

  get '/dashboard', controller: :dashboards, action: :index

  get "/pages/*id" => 'pages#show', as: :pages, format: false
  root 'pages#show', id: 'homepage'
end

app/views/shared/_blank_slate.slim
.blank-slate-container.text-center.spacer-top-10
  = copy

app/views/shared/_chart.html.erb
<canvas id="net-worth-chart" width="400" height="100"></canvas>

<script>
  $(document).ready(function() {
    var ctx = $("#net-worth-chart");
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: <%= raw @net_worth.months.map{|x| "#{l(x.to_date, format: :short)}"} %>,
        datasets: [{
          label: 'Net Worth',
          data: <%= raw @net_worth.amounts %>,
          backgroundColor: 'rgba(255, 99, 132, 0.2)',
          borderColor: 'rgba(255,99,132,1)',
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: { beginAtZero: false }
          }]
        }
      }
    });
  });
</script>

app/views/shared/_footer.slim
footer.row.app-footer
  .columns.small-12.grey
    .text-center 
      h6.inline-block.spacer-right-3 = ENV['APP_NAME']
      = link_to 'Privacy Policy', pages_path('privacy')
      |&nbsp;&middot;&nbsp;
      = link_to 'Terms', pages_path('terms')

app/views/shared/_nav.slim
.top-bar
  .top-bar-left
    ul.dropdown.menu[data-dropdown-menu]
      li.menu-text FI Tracker
      li = link_to "Dashboard", dashboard_path
      li = link_to "Net Worth", financial_accounts_path
      li = link_to "Passive Income", income_sources_path
  .top-bar-right
    ul.menu
      - if user_signed_in?
        li = link_to "Profile", settings_path
        li = link_to 'Account', edit_user_registration_path
        li = link_to 'Sign Out',
          destroy_user_session_path,
          method: 'delete'
      - else
        li = link_to 'Sign In',
          new_user_session_path

app/views/shared/_progress_bar.slim
#progress-container
  .row
    .small-12.large-4.columns
      h4.spacer-top-6 = title
    .small-12.large-8.columns
      .bar.spacer-top-6
        .progress.width-100[style="width: #{progress}%"]
      = "#{numerator} of #{denominator}"