config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      jsonapi_resources :balances, only: [:create, :destroy, :update]
      jsonapi_resources :financial_accounts, only: [:show]
      resource :sessions, only: [:create, :destroy]
    end
  end

  resources :households, only: :update
  resources :user_settings, only: [:update]
  resources :settings, only: [:index]
  resources :income_sources, only: [:create, :edit, :destroy, :index, :update, :new]
  resources :goals, only: [:index, :update]

  resources :assets, only: :show
  resources :liabilities, only: :show
  resources :financial_accounts do
    resources :balances, only: [:create, :destroy, :edit, :index, :show, :update]
    resources :financial_account_users, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :user_invites, only: [:create, :destroy] do
    member do
      put :resend
    end
  end

  get '/dashboard', controller: :dashboards, action: :index

  get "/pages/*id" => 'pages#show', as: :pages, format: false
  root 'pages#show', id: 'homepage'
end

app/models/balance.rb
class Balance < ApplicationRecord
  include UuidToParam

  belongs_to :financial_account, optional: true
  monetize :amount_cents

  validates_presence_of :amount

  scope :newest_first, -> { order(recorded_on: :desc) }
  scope :newest_last, -> { order(recorded_on: :asc) }
  scope :by_month, -> {
    select("date_trunc( 'month', recorded_on ) as month, sum(amount_cents) as amount").group(:month)
  }
end

app/controllers/api/v1/balances_controller.rb
class API::V1::BalancesController < API::V1::BaseController
  def context
    {
      current_user: current_user,
      financial_account: financial_account
    }
  end

  def financial_account
    FinancialAccount.find_by_uuid(params[:financial_account_id])
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_balance, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
    @financial_account = @balance.financial_account
  end

  def create
    @financial_account = current_user.household.financial_accounts.find_by_uuid(
      params[:financial_account_id]
    )

    @balance = @financial_account.balances.create(balance_params)

    respond_to do |format|
      if @balance.save
        format.html { redirect_to financial_account_path(@balance.financial_account), notice: 'Balance was successfully created.' }
        format.json { render :show, status: :created, location: @balance }
      else
        format.html { render :new }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @financial_account = FinancialAccount.find_by_uuid(params[:financial_account_id])

    respond_to do |format|
      format.json { render json: @financial_account.balances.order(:recorded_on) }
    end
  end

  def update
    respond_to do |format|
      if @balance.update(balance_params)
        format.html { redirect_to financial_account_path(@balance.financial_account), notice: 'Balance was successfully updated.' }
        format.json { render :show, status: :ok, location: @balance }
      else
        format.html { render :edit }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @balance.destroy
    respond_to do |format|
      format.html { redirect_to balances_url, notice: 'Balance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_balance
      @balance = Balance.find_by_uuid(params[:id])
    end

    def balance_params
      params.require(:balance).permit(:amount, :recorded_on)
    end
end

app/views/balances/_form.slim
- if @balance.persisted?
  - path = financial_account_balance_path(@financial_account, @balance)
- else
  - path = financial_account_balances_path(@financial_account)
= simple_form_for @balance, url: path do |f|
  - if @balance.errors.any?
    #error_explanation
      h2 = "#{pluralize(@balance.errors.count, "error")} prohibited this balance from being saved:"
      ul
        - @balance.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :amount
    = f.text_field :amount, class: "currency"
  .field
    = f.label :recorded_on
    = f.date_field :recorded_on

  .actions = f.submit "Update", class: "button"

app/views/balances/edit.slim
.row
  .small-12.large-4.columns
    nav[aria-label="You are here:" role="navigation"]
      ul[class="breadcrumbs"]
        li = link_to "Home", root_path
        li = link_to "Net Worth", financial_accounts_path
        li = link_to @financial_account.name, @financial_account
        li
          span.show-for-sr Current:
          |Edit Balance
    h2.strong Edit Balance
    == render 'form'

app/views/balances/index.html.slim
h1 Listing balances

table
  thead
    tr
      th Amount cents
      th Financial account
      th
      th
      th

  tbody
    - @balances.each do |balance|
      tr
        td = balance.amount_cents
        td = balance.financial_account_id
        td = link_to 'Show', balance
        td = link_to 'Edit', edit_balance_path(balance)
        td = link_to 'Destroy', balance, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Balance', new_balance_path

app/views/balances/new.html.slim
h1 New balance

== render 'form'

= link_to 'Back', balances_path

app/views/balances/show.html.slim
p
  strong Balance for
  = link_to @balance.financial_account.name, @balance.financial_account

p
  strong Amount:
  = @balance.amount
p
  strong Recorded on:
  = @balance.recorded_on

= link_to 'Edit', edit_balance_path(@balance)