config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      jsonapi_resources :balances, only: [:create, :destroy, :update]
      jsonapi_resources :financial_accounts, only: [:show]
      resource :sessions, only: [:create, :destroy]
    end
  end

  resources :households, only: :update
  resources :user_settings, only: [:update]
  resources :settings, only: [:index]
  resources :income_sources, only: [:create, :edit, :destroy, :index, :update, :new]
  resources :goals, only: [:index, :update]

  resources :assets, only: :show
  resources :liabilities, only: :show
  resources :financial_accounts do
    resources :balances, only: [:create, :destroy, :edit, :index, :show, :update]
    resources :financial_account_users, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :user_invites, only: [:create, :destroy] do
    member do
      put :resend
    end
  end

  get '/dashboard', controller: :dashboards, action: :index

  get "/pages/*id" => 'pages#show', as: :pages, format: false
  root 'pages#show', id: 'homepage'
end

app/models/income_source.rb
class IncomeSource < ApplicationRecord
  monetize :monthly_amount_cents

  has_one :household_income_source
  has_one :household, through: :household_income_source

  scope :alpha, -> { order(name: :asc) }
end

app/controllers/income_sources_controller.rb
class IncomeSourcesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_income_source, only: [:show, :edit, :update, :destroy]

  def index
    @income_sources = IncomeSourceDecorator.decorate_collection(
      current_user.household.income_sources.alpha
    )
    @household_income_sources = HouseholdIncomeSourceDecorator.decorate(
      HouseholdIncomeSources.new(current_user.household)
    )
  end

  def new
    @income_source = IncomeSource.new
  end

  def edit
  end

  def create
    @income_source = current_user.household.income_sources.new(income_source_params)

    respond_to do |format|
      if @income_source.save
        format.html { redirect_to income_sources_path, notice: 'Income source was successfully created.' }
        format.json { render :show, status: :created, location: @income_source }
      else
        format.html { render :new }
        format.json { render json: @income_source.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @income_source.update(income_source_params)
        format.html { redirect_to income_sources_path, notice: 'Income source was successfully updated.' }
        format.json { render :show, status: :ok, location: income_sources_path }
      else
        format.html { render :edit }
        format.json { render json: @income_source.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @income_source.destroy
    respond_to do |format|
      format.html { redirect_to income_sources_url, notice: 'Income source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_income_source
      @income_source = current_user.household.income_sources.find(params[:id])
    end

    def income_source_params
      params.require(:income_source).permit(:name, :monthly_amount)
    end
end

app/views/income_sources/_form.html.slim
= simple_form_for(@income_source) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :monthly_amount

  .form-actions
    = f.button :submit

app/views/income_sources/edit.html.slim
.row
  .small-12
    nav[aria-label="You are here:" role="navigation"]
      ul[class="breadcrumbs"]
        li = link_to "Home", root_path
        li = link_to "Passive Income", income_sources_path
        li = link_to @income_source.name, @income_source
        li
          span.show-for-sr Current:
          |Edit

    h1
      |Edit&nbsp;
      = @income_source.name

    == render 'form'

app/views/income_sources/index.slim
.row
  .small-12.columns
    nav[aria-label="You are here:" role="navigation"]
      ul[class="breadcrumbs"]
        li = link_to "Home", root_path
        li
          span.show-for-sr Current:
          |Passive Income

    h1.strong Passive Income

    = link_to 'Create Income Source',
      new_income_source_path,
      class: 'button'

    - if @income_sources.any?
      table
        thead
          tr
            th Source
            th Monthly Income
            th
            th

        tbody
          - @income_sources.each do |income_source|
            tr
              td = income_source.name
              td = income_source.amount_to_human
              td = link_to 'Edit', edit_income_source_path(income_source)
              td = link_to 'Delete', income_source, data: { confirm: 'Are you sure?' }, method: :delete
    - else
      = render "shared/blank_slate", copy: "You have no passive income sources. Keep trying!"

= render "shared/progress_bar",
  title: "Passive Income",
  progress: @household_income_sources.progress_rounded,
  numerator: @household_income_sources.passive_income_to_human,
  denominator: @household_income_sources.goal_to_human

app/views/income_sources/new.html.slim
.row
  .small-12.large-6
    h1 Add Passive Income Source
    p Examples include dividends, rental income, or side business.
    == render 'form'

app/views/income_sources/show.html.slim
.row
  .small-12
    nav[aria-label="You are here:" role="navigation"]
      ul[class="breadcrumbs"]
        li = link_to "Home", root_path
        li = link_to "Passive Income", income_sources_path
        li
          span.show-for-sr Current:
          = @income_source.name

    p
      strong Name:
      = @income_source.name
    p
      strong Monthly amount cents:
      = @income_source.monthly_amount_cents

    = link_to 'Edit', edit_income_source_path(@income_source)
    '|
    = link_to 'Back', income_sources_path