config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      jsonapi_resources :balances, only: [:create, :destroy, :update]
      jsonapi_resources :financial_accounts, only: [:show]
      resource :sessions, only: [:create, :destroy]
    end
  end

  resources :households, only: :update
  resources :user_settings, only: [:update]
  resources :settings, only: [:index]
  resources :income_sources, only: [:create, :edit, :destroy, :index, :update, :new]
  resources :goals, only: [:index, :update]

  resources :assets, only: :show
  resources :liabilities, only: :show
  resources :financial_accounts do
    resources :balances, only: [:create, :destroy, :edit, :index, :show, :update]
    resources :financial_account_users, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :user_invites, only: [:create, :destroy] do
    member do
      put :resend
    end
  end

  get '/dashboard', controller: :dashboards, action: :index

  get "/pages/*id" => 'pages#show', as: :pages, format: false
  root 'pages#show', id: 'homepage'
end

app/models/goal.rb
class Goal < ApplicationRecord
  monetize :net_worth_cents, :passive_income_cents
  belongs_to :household
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to settings_path, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_goal
      @goal = current_user.household.goal
    end

    def goal_params
      params.require(:goal).permit(:net_worth, :passive_income)
    end
end

app/views/goals/_form.html.slim
= form_for goal do |f|
  - if goal.errors.any?
    #error_explanation
      h2 = "#{pluralize(goal.errors.count, "error")} prohibited this goal from being saved:"
      ul
        - goal.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :net_worth_goal
    = f.text_field :net_worth, class: "currency"
    p.help-text Amount that can enble you to quit your job and live off of 4% yearly.

  .field
    = f.label :passive_income_goal
    = f.text_field :passive_income, class: "currency"
    p.help-text Amount you wish to earn passively to replace your job.
  .actions = f.submit "Update", class: "button"

app/views/goals/edit.html.slim
h1 Editing goal

== render 'form'

= link_to 'Show', @goal
'|
= link_to 'Back', goals_path

app/views/goals/index.html.slim
.row
  .small-12.large-4
    h1 Goals

    = simple_form_for @goal do |f|
      = f.input :net_worth
      = f.input :passive_income
      = f.button :submit

app/views/goals/new.html.slim
h1 New goal

== render 'form'

= link_to 'Back', goals_path

app/views/goals/show.html.slim
p#notice = notice

p
  strong Net Worth:&nbsp;
  = money_without_cents_and_with_symbol @goal.net_worth
p
  strong Passive income:&nbsp;
  = money_without_cents_and_with_symbol @goal.passive_income

= link_to 'Edit', edit_goal_path(@goal)
'|
= link_to 'Back', goals_path